server:
  port: 8080
  #context-path: /security

spring:
  datasource:
      name: security
      url: jdbc:mysql://localhost:3306/security?characterEncoding=UTF-8
      username: root
      password: 123abc
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat,log4j
      maxActive: 1000
      initialSize: 500
      maxWait: 60000
      minIdle: 500
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      #cachePrepStmts: true 开启二级缓存
      testOnBorrow: true
      testOnReturn: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

security:
  oauth2:
    client:
      client-secret: mosssecret
      client-id: moss

